openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:80  # only for preview function.
  - url: http://172.20.0.6:80 # see "curl" and try in bash.
tags:
  - name: General
    description: The general API for communication with the embedded system
  - name: ELASTIC
    description: communication with elastic via python
  - name: default
    description: default API collection

paths:
  /:
    get:
      description: 
      responses:
        '200':
          description: OK
  /csv2elastic:
    get:
      tags:
        - "ELASTIC"
      description: CSV to Elastic for testing
      responses:
        '200':
          description: OK
  /environment:
    get:
      tags:
        - "General"
      description: Check the environment of the running system
      responses:
        '200':
          description: OK
  /health:
    get:
      tags:
        - "General"
      description: Check the status
      responses:
        '200':
          description: OK
