services:
  mosquitto:
    build:
      args:
        VERSION: 2.0.10
      context: /workspaces/mqtt_docker_test/mosquitto
      dockerfile: Dockerfile.mosquitto
    container_name: mqtt
    image: eclipse-mosquitto-config:2.0.10
    ports:
    - published: 1883
      target: 1883
    - published: 9001
      target: 9001
    restart: always
version: '3.7'

