version: '3.7'

services:

  logstash:
    volumes:
      ###### - ./docker/pipline/:/usr/share/logstash/pipeline
      - ./docker/logstash/:/home/logs/

  grafana:
    volumes:
      - ./docker/datasources/:/etc/grafana/provisioning/datasources/
      - ./docker/dashboards/:/etc/grafana/provisioning/dashboards/
      - ./docker/dashboards/json:/etc/dashboards/

  ubuntu:
    volumes:
      # - ${localWorkspaceFolder}/src/ubuntu/:/usr/src/ubuntu/
      # - ${HOST_PROJECT_PATH}/src/ubuntu/:/usr/src/ubuntu/
      - ./src/ubuntu/:/usr/src/ubuntu/
