version: '3.7'

services: 
  mosquitto:
    image: eclipse-mosquitto-config:${MOSQUITTO_VERS}
    build: 
      context: ./mosquitto/
      dockerfile: Dockerfile.mosquitto
      args:
        - VERSION=${MOSQUITTO_VERS}
    container_name: mqtt
    restart: always
    ports:
      - ${PORT_MOSQUITTO_1}:${PORT_MOSQUITTO_1}
      - ${PORT_MOSQUITTO_2}:${PORT_MOSQUITTO_2}
