version: '3.7'

services: 
  mosquitto:
    image: eclipse-mosquitto:${MOSQUITTO_VERS}
    container_name: mqtt
    restart: always
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - ./docker/mosquitto/config/mosquitto.passwd:/mosquitto/config/mosquitto.passwd
    #   - ./docker/mosquitto/data:/mosquitto/data
    #   - ./docker/mosquitto/log:/mosquitto/log
    ports:
      - ${PORT_MOSQUITTO_1}:${PORT_MOSQUITTO_1}
      - ${PORT_MOSQUITTO_2}:${PORT_MOSQUITTO_2}
    networks:
      backend:
        ipv4_address: ${IPV4_MOSQUITTO}


networks:
  backend:
    ipam:
      config:
        - subnet: ${IPV4_SUBNET}
