version: '3.7'

services:
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: elasticsearch
    environment:
      - node.name=BW_node
      - discovery.type=single-node
      - bootstrap.memory_lock=true          # dev
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"    # dev
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - data01:/usr/share/elasticsearch/data
    cap_add:
      - IPC_LOCK
    ports:
      - ${PORT_ELASTIC_1}:${PORT_ELASTIC_1}
      - ${PORT_ELASTIC_2}:${PORT_ELASTIC_2}
    networks:
      backend:
        ipv4_address: ${IPV4_ELASTICSEARCH} 

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:${PORT_ELASTIC_1}
    ports:
      - ${PORT_KIBANA}:${PORT_KIBANA}
    links:
      - elasticsearch
    networks:
      backend:
        ipv4_address: ${IPV4_KIBANA}

  logstash:
    container_name: logstash
    image: logstash
    build:
      context: .
      dockerfile: ./docker/Dockerfile.logstash
    env_file:
     - ./.env
    ports:
      - ${PORT_LOGSTASH}:${PORT_LOGSTASH}
    depends_on: 
     - elasticsearch
    networks:
      backend:
        ipv4_address: ${IPV4_LOGSTASH}

  grafana:
    container_name: grafana
    image: grafana
    build:
      context: .
      dockerfile: ./docker/Dockerfile.grafana
    ports:
      - ${PORT_GRAFANA}:${PORT_GRAFANA}
    env_file:
     - ./.env
    depends_on: 
      - elasticsearch
    networks:
      backend:
        ipv4_address: ${IPV4_GRAFANA}

  pyserver:
    container_name: pyserver
    image: pyserver
    build:
      context: .
      dockerfile: ./docker/Dockerfile.pyserver
    env_file:
     - ./.env    
    environment:
      - IPV4_ADDR=${IPV4_PYTHON_SERVER}
    ports:
      - ${PORT_DEV_REMOTE_DEBUG}:${PORT_DEV_REMOTE_DEBUG}
      - ${PORT_API}:${PORT_API}
    entrypoint: [ "python3", "-m", "debugpy", "--listen",
     "${IPV4_PYTHON_SERVER}:${PORT_DEV_REMOTE_DEBUG}", "./main.py"]
    stdin_open: true
    tty: true
    networks:
      backend:
        ipv4_address: ${IPV4_PYTHON_SERVER}

volumes:
  data01:
    driver: local

networks:
  backend:
    ipam:
      config:
        - subnet: ${IPV4_SUBNET}
