apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml --out minikube.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: mosquitto
      name: mosquitto
    spec:
      ports:
        - name: "1883"
          port: 1883
          targetPort: 1883
        - name: "9001"
          port: 9001
          targetPort: 9001
      selector:
        io.kompose.service: mosquitto
      type: loadBalancer
      externalIPs:
      - 192.168.178.7
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml --out minikube.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: mosquitto
      name: mosquitto
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: mosquitto
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose-resolved.yaml --out minikube.yaml
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: mosquitto
        spec:
          containers:
            - image: eclipse-mosquitto-config:2.0.10
              name: mqtt
              ports:
                - containerPort: 1883
                - containerPort: 9001
              resources: {}
          restartPolicy: Always
    status: {}
kind: List
metadata: {}

