:toc:
:icons: font
:experimental:
:source-highlighter: pygments
:pygments-style: emacs

= IOT with docker


== working with this project

=== initial

* https://code.visualstudio.com/download[VSC] with https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers[Remote-Containers]

* https://docs.docker.com/docker-for-windows/install-windows-home/[docker on Windows]

.https://www.ssh.com/ssh/keygen/[Copying the Public Key to the Server]
[source, bash]
----
ssh-copy-id -i ~/.ssh/id_rsa.pub user@host
----


=== basic commands

.freeze python requirements
[source, BASH]
----
pip freeze > docker/requirements.txt
----

.start docker container from #outside# the devContainer
[source, CMD]
----
docker-compose -f ./docker-compose.yml up --build --force-recreate -d
----

.stop docker container
[source, BASH]
----
docker-compose -f ./docker-compose.yml down
----

.load development Container in VSC
. kbd:[Ctrl+Shift+P] or kbd:[F1]
. type in : ``Remote-Containers: Reopen in Container``

[IMPORTANT]
The Extension https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers[Remote-Containers] is needed


.overview of environment variables in the project
[subs="attributes"]
----
include::.env[]
----


== docker remote deploying on raspberry

. install a OS on a SD-card

    e.g. UBUNTU SERVER 2.10 64bit

. install https://docs.docker.com/compose/install/#alternative-install-options[docker-compose] and https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository[docker] on raspberry

+
[source, bash]
----
sudo pip install docker-compose
sudo apt install docker.io
----
+

+
[IMPORTANT]
docker-compose installed with pip. Other methods may lead to problems if using "remote" context because of causing a mismatch of OpenSSL versions.
+
. create docker context from Laptop/VSC and proof it
+
[source, bash]
----
docker context create remote --docker "host=ssh://ubuntu@192.168.178.7"

docker context ls

docker context use remote
----
+

[NOTE]
if there are still problems with docker, try to https://github.com/sindresorhus/guides/blob/main/docker-without-sudo.md[add ubuntu user to docker group or have access via SSH for docker daemon ].
+

[NOTE]
SSH key needs to be on the remote machine

+

.copy Project to remote machine / update Project files
[source, bash]
----
scp -r /workspaces/Elastic/ ubuntu@192.168.178.7:/home/ubuntu/ --exclude "SSH" //<1>
rsync -r /workspaces/Elastic/ ubuntu@192.168.178.7:/home/ubuntu/Elastic --delete --exclude "SSH" //<2>
----
<1> copy
<2> update


== links

=== general

https://github.com/FreeOpcUa/opcua-asyncio[python opc ua lib]

== additional commands collection

.copy file via SSH
[source, cmd]
----
scp /path/to/file username@a:/path/to/destination
----

.enter a container
[source, cmd]
----
docker exec -it ubuntu_server bash  
----

.copy folder from inside Dev Container to remote machine
[source, bash]
----
scp -r /workspaces/Elastic/ ubuntu@192.168.178.7:/home/ubuntu/ --exclude "SSH"
----


.start docker from SSH-Remote-Host (Pi) for production
[source, bash]
----
docker-compose -f docker-compose.yml -f docker-compose.arm.yml -f docker-compose.prod.yml -f docker-compose.local.yml up --build --force-recreate -d
----

.start docker from localhost (windows/devcontainer) on remote-host via SSH 
[source#hello, bash]
----
docker-compose -H ssh://ubuntu@192.168.178.7 -f docker-compose.yml -f docker-compose.arm.yml -f docker-compose.prod.yml up --build --force-recreate -d 
----

.add local bind-mounts. Makes Hot-deployment possible
[source, bash]
----
docker-compose -f ./docker-compose.yml -f ./docker-compose.local.yml up --build --force-recreate -d
----

== todo

docker-compose -f docker-compose.yml  up --build --force-recreate -d

docker-compose -f docker-compose.yml  down







############ new

docker-compose -f ./docker-compose.yml up --build --force-recreate -d
User:"devUser"
PW:
"nrg0njvkfr94tngfJBNBNEINBE§h7h0r_30k94jt39jt#+***43Q"

https://centurio.net/2019/12/16/configure-mosquitto-mqtt-broker-user-authentication-in-docker-running-on-synology-nas/


https://mosquitto.org/documentation/authentication-methods/

https://mosquitto.org/documentation/dynamic-security/#configuring-default-access

https://mosquitto.org/documentation/migrating-to-2-0/

https://github.com/thelebster/example-mosquitto-simple-auth-docker/blob/master/Dockerfile

https://github.com/eclipse/mosquitto/tree/1c79920d78321c69add9d6d6f879dd73387bc25e/docker/2.0-openssl

https://github.com/eclipse/mosquitto/blob/1c79920d78321c69add9d6d6f879dd73387bc25e/docker/2.0/Dockerfile
