:toc:
:icons: font
:experimental:
:source-highlighter: pygments
:pygments-style: emacs

= IOT with docker


== working with this project

=== initial

* https://code.visualstudio.com/download[VSC] with https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers[Remote-Containers]

* https://docs.docker.com/docker-for-windows/install-windows-home/[docker on Windows]



=== basic commands

.freeze python requirements
[source, BASH]
----
pip freeze > docker/requirements.txt
----

.start docker container from #outside# the devContainer
[source, CMD]
----
docker-compose -f ./docker-compose.yml up --build --force-recreate -d
----

.stop docker container
[source, BASH]
----
docker-compose -f ./docker-compose.yml down
----

.load development Container in VSC
. kbd:[Ctrl+Shift+P] or kbd:[F1]
. type in : ``Remote-Containers: Reopen in Container``

[IMPORTANT]
The Extension https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers[Remote-Containers] is needed


.overview of environment variables in the project
[subs="attributes"]
----
include::.env[]
----


== docker remote deploying on raspberry

. install a OS on a SD-card

    e.g. UBUNTU SERVER 2.10 64bit

. install https://docs.docker.com/compose/install/#alternative-install-options[docker-compose] and https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository[docker] on raspberry

+
[source, bash]
----
sudo pip install docker-compose
sudo apt install docker.io
----
+

+
[IMPORTANT]
docker-compose installed with pip. Other methods may lead to problems if using "remote" context because of causing a mismatch of OpenSSL versions.
+
. create docker context from Laptop/VSC and proof it
+
[source, bash]
----
docker context create remote --docker "host=ssh://ubuntu@192.168.178.7"

docker context ls

docker context use remote
----
+

[NOTE]
if there are still problems with docker, try to https://github.com/sindresorhus/guides/blob/main/docker-without-sudo.md[add ubuntu user to docker group or have access via SSH for docker daemon ].
+

[NOTE]
SSH key needs to be on the remote machine

+

.copy Project to remote machine / update Project files
[source, bash]
----
scp -r /workspaces/Elastic/ ubuntu@192.168.178.7:/home/ubuntu/ --exclude "SSH" //<1>
rsync -r /workspaces/Elastic/ ubuntu@192.168.178.7:/home/ubuntu/Elastic --delete --exclude "SSH" //<2>
----
<1> copy
<2> update


== links

https://github.com/microsoft/vscode-dev-containers/tree/master/containers/kubernetes-helm[kubernetes for devcontainer]

https://www.it.iitb.ac.in/frg/wiki/images/b/b5/P3_FRG_REPORT.pdf[describe kompose]

https://opensource.com/article/20/6/kubernetes-raspberry-pi[on rpi]

https://www.zepworks.com/posts/access-minikube-remotely-kvm/[Remote to Minikube]

https://github.com/kubernetes/kompose/blob/master/docs/getting-started.md[getting started with kompose]

https://dev.to/gvelrajan/configure-local-kubectl-to-remote-access-kubernetes-cluster-2g81[configure local kubectl to remote access kubernetes cluster]

=== general

https://github.com/FreeOpcUa/opcua-asyncio[python opc ua lib]

== additional commands collection

.copy file via SSH
[source, cmd]
----
scp /path/to/file username@a:/path/to/destination
----

.enter a container
[source, cmd]
----
docker exec -it ubuntu_server bash  
----

.copy folder from inside Dev Container to remote machine
[source, bash]
----
scp -r /workspaces/Elastic/ ubuntu@192.168.178.7:/home/ubuntu/ --exclude "SSH"
----


.start docker from SSH-Remote-Host (Pi) for production
[source, bash]
----
docker-compose -f docker-compose.yml -f docker-compose.arm.yml -f docker-compose.prod.yml -f docker-compose.local.yml up --build --force-recreate -d
----

.start docker from localhost (windows/devcontainer) on remote-host via SSH 
[source#hello, bash]
----
docker-compose -H ssh://ubuntu@192.168.178.7 -f docker-compose.yml -f docker-compose.arm.yml -f docker-compose.prod.yml up --build --force-recreate -d 
----

.add local bind-mounts. Makes Hot-deployment possible
[source, bash]
----
docker-compose -f ./docker-compose.yml -f ./docker-compose.local.yml up --build --force-recreate -d
----

### new


== working with mosquitto - mqtt

=== links

https://centurio.net/2019/12/16/configure-mosquitto-mqtt-broker-user-authentication-in-docker-running-on-synology-nas/[mosquitto server with docker - user authentication]

https://mosquitto.org/documentation/authentication-methods/[mosquitto - Authentication - Passwordfile]

== using docker-compose

=== commands

.docker up
[source, bash]
----
docker-compose -f ./docker-compose.yml up --build --force-recreate -d
----

.docker down
[source, bash]
----
docker-compose -f docker-compose.yml  down
----




== install kubernetes / minikube / kubectl

https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/#install-kubectl-binary-with-curl-on-windows[install kubectl]

https://www.docker.com/blog/docker-windows-desktop-now-kubernetes/[kubectl with Docker Desktop]

https://kubernetes.io/de/docs/tasks/tools/install-minikube/[install kubectl]

https://chocolatey.org/install[install chocolatey]


[source, powershell]
----
Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform
----

.start minikube on windows
[source, powershell]
----
minikube start
----

.check if file exists on remote host
[source, bash]
----
ssh ubuntu@192.168.178.7 test -f "~/.kube/config"
----

.mqtt commands
[source, bash]
----
mosquitto_sub -t "test" -h 192.168.178.7 -u "devUser" -P "nrg0njvkfr94tngfJBNBNEINBE§h7h0r_30k94jt39jt#+***43Q" # <1>
mosquitto_pub -t "test" -h 192.168.178.7 -u "devUser" -P "nrg0njvkfr94tngfJBNBNEINBE§h7h0r_30k94jt39jt#+***43Q" -m "myMessage" # <2>
----
<1> subscribe to mqtt-broker
<2> publish to mqtt broker

.generate kubernetes manifest from docker-compose on the Raspberry
[source, bash]
----
docker-compose config > docker-compose-resolved.yaml && kompose convert -f docker-compose-resolved.yaml --volumes hostPath --out minikube.yaml
----

.add to the ``minikube.yaml`` to the service
[source, minikube.yaml]
----
      selector:
        io.kompose.service: mosquitto
      type: LoadBalancer
      externalIPs:
      - 192.168.178.7 # <1>
----
<1> IP of the Raspberry Pi

.deyploy service to minikube
[source, bash]
----
kubectl apply -f minikube.yaml
----

[NOTE]
if there is an Error X509 you can try kubectl wit ``--insecure-skip-tls-verify`` flag


.examples for kubectl use
[source, bash]
----
kubectl get svc hello-minikube # <1>
kubectl delete svc hello-minikube # <2>
kubectl delete deployments hello-minikube # <2>
kubectl create deployment hello-minikube --image=gcr.io/google_containers/echoserver:1.4 --port=8080 # <3>
kubectl expose deployment hello-minikube --type=LoadBalancer --port 8080 # <3>
kubectl describe svc mosquitto # <4>
----
<1> get service
<2> delete
<3> creat and than expose
<4> infos about a service

.init dashboard if necessary
[source, bash]
----
minikube dashboard
----

after URL is shown you can end it with kbd:[Ctrl+C]

.enable the dashboard proxy to view the dashboard remotely
[source, bash]
----
kubectl proxy --address='0.0.0.0' --disable-filter=true
----

Now you can enter the dashboard via the URL ``http://192.168.178.7:8001/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy`` when the command was entered on the host. For entering the command in the devContainer edit the hostname / IP to ``localhost`` so the URL ist ``http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy``

[NOTE]
the port musst be open. Check if ``8001`` ist open. If not, open it via the Firewall rule. e.g. ``sudo ufw allow 8001`` on ubuntu




https://www.docker.com/blog/simplifying-kubernetes-with-docker-compose-and-friends/[dnsrr]

https://spectechular.de/post/lokalen-mqtt-server-mit-docker-betreiben/

.creating passwordfile with User ``devUser``
[source, bash]
----
mosquitto_passwd -c mosquitto.passwd devUser
----

example here:

  User:"devUser"
  PW:"nrg0njvkfr94tngfJBNBNEINBE§h7h0r_30k94jt39jt#+***43Q"


== todo

=== ms install

----
choco install minikube kubernetes-cli
----

minikube start


https://github.com/kubernetes-sigs/kind/issues/566[workaround for docker from docker - kubectl]

try ## https://codingbee.net/tutorials/kubernetes/using-docker-with-minikube[docker with minikube]

https://alexellisuk.medium.com/walk-through-install-kubernetes-to-your-raspberry-pi-in-15-minutes-84a8492dc95a[kubernetes - RPi - dashboard]

https://stackoverflow.com/questions/44519980/assign-external-ip-to-a-kubernetes-service[add external ip]


== remote connect to kubectl

For connecting to a remote machine you can run the following script. Change hostname / IP to your environment.

.connfig load execute in devContainer
[source, bash]
----
./install/loadConfigToContainer.sh 
----

You can check if it works with running ``kubectl get svc``. If there are Problems you will get an message: ``Unable to connect to the server: x509:``


== install on Raspberry pi

. set up an RPi with a Ubuntu image (Server Version 21.04 or higher - 64 bit) with https://www.raspberrypi.org/software/[Raspberry Pi Iamger]

. establish an ssh connection to your Pi
+

.https://www.ssh.com/ssh/keygen/[Copying the Public Key to the Server]
[source, bash]
----
ssh-copy-id -i ~/.ssh/id_rsa.pub user@host # <1>
ssh-copy-id -i ./SSH/id_rsa.pub ubuntu@192.168.178.7 # <2>
----
<1> general
<2> this project

+
. sync the Project to your pi
+

.copy Project to remote machine / update Project files
[source, bash]
----
rsync -r /workspaces/mqtt_docker_test/ ubuntu@192.168.178.7:/home/ubuntu/mqtt_docker_test --delete --exclude "SSH" 
----

+
. setup docker with script if needed
+

[source, bash]
----
cd /home/ubuntu/mqtt_docker_test/
./install/setupDocker.sh
----
+
. setup minikube with script if needed
+

[source, bash]
----
cd /home/ubuntu/mqtt_docker_test/
./install/setupMiniKube.sh
----

+
. now you can work with minikube 

.check if your System is working.
[source, bash]
----
minikube ip
----
