FROM jamesgarside/logstash:7.9.3


# copy a loglife for investigation
COPY docker/logstash/ /home/logs/


RUN rm -f /usr/share/logstash/pipeline/logstash.conf

# ADD ./docker/logstash/logstash.yml /usr/share/logstash/config/logstash.yml
ADD ./docker/logstash/logstash.conf /usr/share/logstash/pipeline/logstash.conf