version: '3.7'

services:
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: elasticsearch
    environment:
      - node.name=BW_node
      #- xpack.security.enabled=true
      #- ELASTIC_PASSWORD=${PASSWORD}
      #- ELASTICSEARCH_USERNAME=${USERNAME}
      #- http.cors.enabled=true
      #- http.cors.allow-origin=*
      #- http.host=0.0.0.0
      #- transport.host= 127.0.0.1
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      frontend:
        ipv4_address: 172.20.0.3  

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      #- xpack.security.enabled=true
      #- ELASTIC_PASSWORD=${PASSWORD}
      #- ELASTICSEARCH_USERNAME=${USERNAME}
    ports:
      - 5601:5601
    links:
      - elasticsearch
    networks:
      frontend:
        ipv4_address: 172.20.0.4  

  grafana:
    container_name: grafana
    image: grafana/grafana:7.3.0
    ports:
      - 3000:3000
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./dashboard.json:/etc/dashboards/dashboard.json
    depends_on: 
      - elasticsearch
    networks:
      frontend:
        ipv4_address: 172.20.0.5


volumes:
  elasticsearch-data:
    driver: local

networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24
