FROM jamesgarside/logstash:7.9.3

# copy a loglife for investigation
COPY docker/logstash/ /home/logs/

RUN rm -f /usr/share/logstash/pipeline/logstash.conf

ADD ./docker/logstash/settings/ /usr/share/logstash/config/
ADD ./docker/logstash/conf/ /usr/share/logstash/pipeline/