# config file version
apiVersion: 1

datasources:
  - name: Elastic
    type: elasticsearch
    access: proxy
    database: "countryvaccinations"
    url: http://${IPV4_ELASTICSEARCH}:${PORT_ELASTIC_1}
    jsonData:
      timeField: "@timestamp"
      esVersion: 70
      interval: null
  - name: Elastic_test
    type: elasticsearch
    access: proxy
    database: "datatest"
    url: http://${IPV4_ELASTICSEARCH}:${PORT_ELASTIC_1}
    jsonData:
      timeField: "@timestamp"
      esVersion: 70
      interval: null
  - name: ElasticLogstash
    type: elasticsearch
    access: proxy
    database: "testindexlogstash"
    url: http://${IPV4_ELASTICSEARCH}:${PORT_ELASTIC_1}
    jsonData:
      timeField: "time"
      esVersion: 70
      interval: null
      logMessageField: log
